Unify exception handling
gridsuite/gridapp-template pull request #35
Opened 2022-11-29 09:56 UTC by ayolab

Signed-off-by: Ayoub LABIDI <ayoub.labidi@protonmail.com>

2022-11-29 10:37 UTC, laurgarn requested changes

2022-11-29 10:37 UTC, laurgarn commented on src/utils/rest-api.js
> +            else if (response.status === 204) return false;
Missing a case, there. Either a return or a throw. This one is blocking for me.

2022-11-29 10:37 UTC, laurgarn commented on src/utils/rest-api.js
> +function handleResponse(response, isJson) {
I'd prefer 'expectsJson' over 'isJson', everywhere the returned value is expected to match a json structure.

2022-11-30 09:27 UTC, laurgarn approved these changes
Seems good.

2022-12-01 12:11 UTC, SlimaneAmar approved these changes

2022-12-08 16:45 UTC, merged